server:
  port: 9002
spring:
  application:
    name: server
  redis:
      host: 39.106.204.4
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.204.4:33306/course?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.shop.all.pojo
#  mapper-locations: classpath:com.shop.all.dao/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#jwt
jwt:
  config:
    key: mindy
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
workerId: 0
datacenterId: 0
